Homework 1
================
Nikhita Damaraju

This is my solution to Homework 1.

``` r
library(tidyverse)
```

    ## ── Attaching packages ──────────────────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ── Conflicts ─────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(palmerpenguins)
```

\#\#Problem 1

Create a data frame with the specified elements

``` r
prob1_df =
  tibble(
  samp = rnorm(10),
  samp_gt_0 = samp > 0,
  char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
  factor_vec = factor(c("low", "low", "low", "mod", "mod", "mod", "mod", "high", "high", "high"))
)
```

Take the mean of each variable in prob1\_df

``` r
mean(pull(prob1_df, samp))
```

    ## [1] -0.3279998

``` r
mean(pull(prob1_df, samp_gt_0))
```

    ## [1] 0.4

``` r
mean(pull(prob1_df, char_vec))
```

    ## Warning in mean.default(pull(prob1_df, char_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(prob1_df, factor_vec))
```

    ## Warning in mean.default(pull(prob1_df, factor_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

The mean of character and factor vectors cannot be taken. The logical
vector is converted to numeric using implicit type conversion where TRUE
is taken as 1 and FALSE, 0.

Convert each variable in prob1\_df to numeric

``` r
as.numeric(pull(prob1_df, samp))
```

    ##  [1]  0.3057086 -0.7822533 -0.7489377 -0.6749192 -0.4763873 -0.6439278
    ##  [7] -1.9707904  0.1018153  0.3821531  1.2275405

``` r
as.numeric(pull(prob1_df, samp_gt_0))
```

    ##  [1] 1 0 0 0 0 0 0 1 1 1

``` r
as.numeric(pull(prob1_df, char_vec))
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(pull(prob1_df, factor_vec))
```

    ##  [1] 2 2 2 3 3 3 3 1 1 1

Note: Logical vector is converted to numeric where TRUE is taken as
numeric 1 and FALSE, numeric 0. Character vector cannot be converted to
numeric and NAs are introduced by coercion. Factor vector is converted
to numeric where low is treated as 2, mod as 3 and high as 1. Numbers
from 1 to 3 are assigned in order of increasing frequency of a factor
level.

Converting and multiplying logical vector

``` r
as.numeric(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
```

    ##  [1] 0.3057086 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000 0.0000000
    ##  [8] 0.1018153 0.3821531 1.2275405

``` r
as.factor(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
```

    ## Warning in Ops.factor(as.factor(pull(prob1_df, samp_gt_0)), pull(prob1_df, : '*'
    ## not meaningful for factors

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(as.factor(pull(prob1_df, samp_gt_0))) * pull(prob1_df, samp)
```

    ##  [1]  0.6114172 -0.7822533 -0.7489377 -0.6749192 -0.4763873 -0.6439278
    ##  [7] -1.9707904  0.2036306  0.7643063  2.4550810

Note: Converting to numeric and multiplication with random sample (samp)
produces a numeric vector result. However, converting to factor and
performing the same multiplication leads to an error message and
introduction of NAs. Converting to factor and then to numeric leads to
the end result being a numeric vector that can be multiplied by samp.

\#\#Problem 2

Loading penguins dataset

``` r
data("penguins", package = "palmerpenguins")
```

Summary of penguins dataset

``` r
head(penguins)
```

    ## # A tibble: 6 x 8
    ##   species island bill_length_mm bill_depth_mm flipper_length_… body_mass_g sex  
    ##   <fct>   <fct>           <dbl>         <dbl>            <int>       <int> <fct>
    ## 1 Adelie  Torge…           39.1          18.7              181        3750 male 
    ## 2 Adelie  Torge…           39.5          17.4              186        3800 fema…
    ## 3 Adelie  Torge…           40.3          18                195        3250 fema…
    ## 4 Adelie  Torge…           NA            NA                 NA          NA <NA> 
    ## 5 Adelie  Torge…           36.7          19.3              193        3450 fema…
    ## 6 Adelie  Torge…           39.3          20.6              190        3650 male 
    ## # … with 1 more variable: year <int>

``` r
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
mean(pull(penguins, flipper_length_mm))
```

    ## [1] NA

``` r
mean(na.omit(pull(penguins, flipper_length_mm)))
```

    ## [1] 200.9152

Short description of penguins dataset: 1. Data in the dataset There are
8 columns in this dataset namely: species, island, bill\_length in mm,
bill\_depth in mm, flipper length in mm, body\_mass in grams, sex and
year

2.  The size of the dataset is 344 rows \* 8 columns

3.  Values of important variables

<!-- end list -->

  - Species and Island: There are 3 different types of species of
    penguins in the dataset that live on 3 different islands.
  - Sex: Overall, there are 165 female penguins and 168 male penguins
    with 11 rows where the sex is unknown.
  - Body measurements: bill\_length\_mm, bill depth\_mm,
    flipper\_length\_mm and body\_mass\_g contain 2 missing (NA) values.

<!-- end list -->

4.  Mean of flipper length: The mean of the flipper length results in a
    NA outcome due to the presence of 2 NA values in the column as seen
    in the summary function. However, on excluding the 2 rows with the
    NA values, the mean length is 200.9 mm.

Scatter plot of flipper length vs bill length

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_nd2674_files/figure-gfm/scatter-1.png)<!-- -->

``` r
ggsave("scatter_plot_problem2.pdf", height = 4, width = 6)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).
